version: '3.9'

services:
  app:
    container_name: vue-memo-app
    build:
      context: ./app
      dockerfile: Dockerfile
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - ./app:/usr/src/app
    ports:
    - "8080:8080"
